### ISSUE TITLE
Bug with hidden conteiner

### ISSUE THREAD

**Issue by cawa-93** [desandro/masonry#1008]
If the container is initially hidden, the blocks are not aligned correctly. I expected that the blocks would be a grid, regardless of whether I saw the container now or not.

**Test case:** https://codepen.io/cawa-93/pen/OxKLoY

**Comment by LordPachelbel** [comment]
We recently built a megamenu using Masonry and had the same issue because the menus aren't visible when the page loads, so we did this as a workaround:

```
// initialize Masonry
$('.mega-menu').addClass('open');      // display the mega menus so Masonry has height values to work with
$('.grid').masonry({
  'fitWidth': true
});
$('.mega-menu').removeClass('open');  // hide them again
```
We're still having layout problems, though, if a menu isn't visible when the viewport is resized. We might have to use the show/hide trick there, too.

**Comment by desandro** [comment]
The content in the hidden tabs is hidden, therefore Masonry cannot properly measure the items for layout.

Possible solutions:
- trigger `layout` before you set up the tabs or hidden content.
- trigger `layout` on related content when that tab is selected.

**Comment by LordPachelbel** [comment]
Thank you! Instead of using the open/close trick we're now calling `.masonry('layout')` in our menu's click event handler. It solved both our problems.
