### ISSUE TITLE
Appended item hidden by viewport

### ISSUE THREAD

**Issue by diegosomar** [desandro/masonry#1081]
When I append an item, it goes to the top of the available space. But this space is out of viewport.
See this reduced case:
[https://codepen.io/anon/pen/MLvxJZ](https://codepen.io/anon/pen/MLvxJZ)

Use editor view at the right position and with width 770px. Scroll to bottom and click on the button to append a new item. Note that the new item is under item 13 (invisible area, outside viewport). I think the correct position is side by side with item 16.

PS: Alignment of items is disorganized on purpose.

I appreciate any help.

**Comment by desandro** [comment]
Thanks for reporting this issue. Unfortunately, that's how Masonry is designed to work. If there is a short column available, an appended item will be placed into it.

If you need new items to appear at the bottom, you could create new Masonry instance and append to that, rather than appending to the previous.
