### ISSUE TITLE
Multiple masoned containers on a page

### ISSUE THREAD

**Issue by tchopshop** [desandro/masonry#161]
Forgive me if this is obvious, but I've searched all the issues and examples and cannot find what I need... I'd like to have two different containers "masoned" on the same page... they are separated by a title, so for example I have 

Albums

{container with images for albums}

Singles

{container with smaller images for singles}

I don't want the singles overrunning the album section, I need them to stay separated.
thank you,
Elena

**Comment by rbosneag** [comment]
What if one needs to specify the parent for multiple containers instead of child elements? 
I have a page with 3 tabs and each tab holds a masonry container whose child elements have the same classes applied so we cannot select by bricks (they are defined identical and they share the same page but in different div's). Any workarounds for that?

Great solution for a great product, anyway!
