### ISSUE TITLE
masonry not working properly until resize

### ISSUE THREAD

**Issue by tanerf82** [desandro/masonry#619]
i used masonry layout to list  post thumbnails etc like tetris.

but when page loads, at first, masonry acts false,
and when i resize the window (at least 1px), it fits perfect and layout becomes as it should be.
 here is the link: http://og.ekowww.com

**Comment by jamiemitchell** [comment]
Hi Desandro !

I realise this is an old comment, but after a day or so looking for an answer I just stumbled on this.

having the same sort of issue, my container is 100% width and my items are 33.33333% width, so completely fluid

but on page load there is a gap of about 3-4px, when I open firebug or resize the window, the items align themselves properly

I have tried using percentPosition: true and this helps to within about 1px, but not perfect and the bottom space of the items is still out.

so I tried loading masonry only after images have loaded, now this solves the alignment issue and everything is pixel perfect...but, because it's loading items after, the items jump slightly to the left on page load

any thoughts?

thanks!
