### ISSUE TITLE
Houston, we have a problem! ;)

### ISSUE THREAD

**Issue by php11i5** [desandro/masonry#677]
https://github.com/desandro/masonry/issues/443
look at this! ↑

**Comment by php11i5** [comment]
![x](https://cloud.githubusercontent.com/assets/8140713/6555801/f4c6e61e-c692-11e4-8a58-979baec44dae.PNG)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

It looks like this may be caused by the scroll bar. Try adding `html { overflow-y: scroll; }` to your CSS.

**Comment by php11i5** [comment]
Thanks!
it works!
Packery has the same problem! I will  try to add `html { overflow-y: scroll; }`

**Comment by desandro** [comment]
Thanks for following up!
