### ISSUE TITLE
Layout not right until i resize the window

### ISSUE THREAD

**Issue by ukscotth** [desandro/masonry#694]
Hi,

Im trying to use this with a wordpress theme but when the page first loads the layout is slightly wrong as seen in pic1, when i resize the browser however the layout is fixed like in pic2. Any ideas ?

Thanks,

Scott.

![pic1](https://cloud.githubusercontent.com/assets/10211827/7367778/eab910d8-ed99-11e4-85b2-646a62970748.png)

![pic2](https://cloud.githubusercontent.com/assets/10211827/7367771/dbf93eb0-ed99-11e4-882b-ede3d190056c.png)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by ukscotth** [comment]
Hey, thanks for your reply. I cant seem to replicate it on codepen but this shows a similar type of thing where there is a small gap between the columns on first load but when you resize the browser the gaps dissapear, is there anyway to simulate a browser resize to kind of kick it all into shape ? http://codepen.io/ukscotth/pen/YXPdNK

**Comment by ukscotth** [comment]
i also always have my browser on 125% zoom, not sure if that would make a difference

**Comment by caldcyn** [comment]
I'm having the same issue. I'm using the Weaver Xtreme theme on WordPress. From what I'm seeing visually as the page loads, it seems that the brick size calculation is being done too early? It seems to be initially displaying the bricks using the default font size for the content area, and then refreshing with my brick font size override (which is smaller than the default, that I specify in my child theme's style.css). When using the new font size, the size of the brick itself is resized properly, but the position of the bricks isn't updated. Resizing the browser fixes it. I tried changing my override font size to a larger size (bigger than the content default) and this results in overlap instead of the gaps, so I know it is related to this. I wish I could help narrow it down more, but I'm still a bit new to the WP backend so trying to pinpoint where it is all going wrong is beyond my skills at the moment. I don't know why all of the CSS rules wouldn't have be loaded yet. Maybe it's a theme issue?

**Comment by desandro** [comment]
@ukscotth The gap may be caused by a scrollbar appearing. Try adding `html { overflow-y: scroll; }` to your CSS.
