### ISSUE TITLE
items transition their vertical position on resize

### ISSUE THREAD

**Issue by danielschmid** [desandro/masonry#703]
Despite the fact that i'm using `percentPosition: true` the items transition their vertical position while resizing. Is there a way to prevent that behaviour ? 

![quickcast-16-05-2015-01-24-30](https://cloud.githubusercontent.com/assets/2499648/7668224/7280d550-fc2c-11e4-9a24-1574fe51b964.gif)

**Comment by desandro** [comment]
Nice gif! Thanks for reporting this issue. The transitions are occurring because their vertical position changes, as they are proportional to image size. You can disable all transitions with `transitionDuration: 0`, but you'll still see the vertical position change. This behavior reduces redraw and improves performance.

Closing as `won't fix`

**Comment by danielschmid** [comment]
Ok. Thats what i thought. Thank you.
