### ISSUE TITLE
Slight overlapping/gaps

### ISSUE THREAD

**Issue by alexelash** [desandro/masonry#746]
Hey! 

I'm using masonry to layout various thumbnails of different proportions (1x1, 1x2, 1x3, 2x1, etc) in a seamless grid. The design calls for a 1px gutter for the thumbnails. I gave masonry _gutter: 0_ and then add a white _outline: 1px solid white;_ around each thumbnail. My issue is that there are some slight overlaps. 

<img width="1172" alt="screen shot 2015-08-25 at 12 12 09 am" src="https://cloud.githubusercontent.com/assets/5672295/9458629/72f2b1da-4abe-11e5-9941-73c9ac99270b.png">

I've tried different variations, including adding _gutter: 1_ and no outline, but I haven't had success. However, I've noticed that if I play with the z-index of different thumbnails, then I can sort of tuck them away properly. Haven't come across any real solution. Is this something you have maybe seen before? I'm happy to make a fiddle if needbe.

**Comment by alexelash** [comment]
I actually did more google searches, and eventually found your CodePen entitled [Gaps over Overlaps](http://codepen.io/desandro/pen/NqpEbK). Using __width: calc( 25% - 1px );__ totally solved my overlapping issue, though now I have some sizable gaps to take care of (which i think may be unrelated to this plugin, as the gaps are on .grid-items that are some sort of third. Thanks!

**Comment by alexelash** [comment]
Okay, sorry, closed this too soon. It does still seem as though there is still overlapping. Unfortunately, it's in the same places as in the screenshot about, so essentially nothing has changed despite adding the __width: calc( 25% - 1px );__. Any ideas?

**Comment by desandro** [comment]
Hi there! Thanks for reporting this issue. Aw man, 1px gutters are hard if they have to be exactly 1px. The problem is pixel rounding. While a pure CSS layout can to 1px consistently, using a JavaScript layout will cause gaps and overlaps of 1px sometimes.

There's not going to be a perfect solution. You can either try to remove the gutters alltogether with the Gaps with Overlaps demo, or make the gutters bigger, like 3px, so the pixel rounding errors is less noticeable. Sorry about that!

**Comment by alexelash** [comment]
Aw, womp womp. Yeah, I figured it might just be the inflexibility of the gutter size. Thanks though!
