### ISSUE TITLE
.grid-item--width2 not working

### ISSUE THREAD

**Issue by ungeruehrt** [desandro/masonry#766]
Hi,

I reduced my test case to the very minimum of css and the grid is still not working correctly (all grid-items are displayed one underneath each other instead of being displayed masonry-like). I’d be happy if you could take a look at it again:

http://codepen.io/ungeruehrt/pen/zvKPmo

**Comment by desandro** [comment]
See http://codepen.io/desandro/pen/JYRpQY

1. Use a separate sizing element, like `.grid-sizer`, instead of an item element. Your example used `.arbeitsbild`. The first `.arbeitsbild` was also `.arbeitsbild--width2`, so it was 100% width.

2. imagesLoaded needs an element argument, `imagesLoaded( element, function() {...});`

Revised code looks like 

``` js
docReady( function() {
  var msnry = new Masonry( '.medien', {
    // options
    itemSelector: '.arbeitsbild',
    columnWidth: '.grid-sizer'
  });
  imagesLoaded( '.medien', function() {
    msnry.layout();
  })
});
```
