### ISSUE TITLE
Column width, gutter functions

### ISSUE THREAD

**Issue by DavidSvetlik** [desandro/masonry#772]
Possibility to use selector for columnWidth, gutter etc. is nice, but it would be even nicer if value could be also a function returning value, like that

columnWidth: '.grid-sizer',
gutter: function(rootElement) { return calculatedGutter(); },
itemSelector: '.grid-item'

**Comment by desandro** [comment]
Thanks for this suggestion. Masonry v2 actually used this pattern for columnWidth. But I found it buggy

1.  Measurement with JS and CSS media query can be different.
2. Sizing logic that's usually in CSS is no in JS — duplicating it.

That's why [Masonry v3 uses element sizing](http://masonry.desandro.com/options.html#element-sizing).
