### ISSUE TITLE
Animating Grid Items' Position

### ISSUE THREAD

**Issue by echezbro** [desandro/masonry#773]
@desandro - Firstly, thanks so much for the beautiful plugin, it's truly incredible.

I have a quick question - is there any way, on a 6 x 3 image grid, to *not* have any grid images shift down or off the grid when animated? The animation works perfectly on the centered grid items but seems to fail/flicker on bottom and corner grid items.

- columnWidth: 230px
- grid-item height/width: 230px
- grid-item.isExpanded: 460px

Here's a screencast (*with* $grid.masonry(); being called at the end): http://g.recordit.co/3yZiu0ukhd.gif

Here's a screencast (*without* $grid.masonry(); being called at the end): http://g.recordit.co/V9qSIOcw8H.gif

Any help would be greatly appreciated!

Thanks!

**Comment by desandro** [comment]
You may want to try out [Packery, which has `fit` method](http://packery.metafizzy.co/methods.html#fit) so that expanded content stays where it previously was.  Otherwise, it appears you may want to use an overlay that is positioned top of the masonry content, rather than shifting around the masonry content.
