### ISSUE TITLE
Masonry + Bootstrap + max-width

### ISSUE THREAD

**Issue by maitriya** [desandro/masonry#803]
Using Masonry with Bootstrap and masonry container is placed inside a div with max-width specified:

    <div style="max-width: 710px;">

When resizing browser window items overlap each other: http://codepen.io/anon/pen/obGbrp
Open at 1280 resolution and try to resize browser window.

**Comment by desandro** [comment]
Thanks for reporting this bug. Before triggering layout on window resize, Masonry will check the width of the container element. Since the width of the container element does not change once it hits its max width, layout is not triggered.

We can hack a solution, overwriting `needsResizeLayout`. See demo http://codepen.io/desandro/pen/VeMjeo

``` js
    var msnry = $container.data('masonry');
    msnry.needsResizeLayout = function() {
      return true;
    };
```

**Comment by maitriya** [comment]
You are awesome. Thank you.
