### ISSUE TITLE
Using masonryv3 with ionic - Uncaught Error: Cannot find module 'jquery'

### ISSUE THREAD

**Issue by pliablepixels** [desandro/masonry#805]
Hello,
I am trying to use masonryv3 with an ionic app.
To the best of my knowledge, ionic uses some form of jq-lite not jq

Given that masonryv3 does not need jquery, I thought of using it with my ionic app

The error I keep getting is:
Uncaught Error: Cannot find module 'jquery'

I read elsewhere that masonry tries to detect if jquery is loaded and if so, uses jquery. I am not sure if jquery-lite is causing issues, so I tried to load masonry before ionic bundle js but even in that case - irrespective of whether I load masonry.pkg.min.js before or after, I get the same error

Any thoughts?

**Comment by desandro** [comment]
Sorry to hear you're running into trouble with Masonry. If are you using `masonry.pkgd.js`, then it includes jquery-bridget. If jQuery is present, jquery-bridget will setup Masonry as a plugin. If jQuery is not present, it skips over this.

I'm not familiar with Ionic, so I'm not sure where the problem is occurring.

**Comment by pliablepixels** [comment]
Thank you - is there a change I can make that does not check for jquery? That is - assumes only vanilla JS.

**Comment by pliablepixels** [comment]
I am using masonry.pkgd.js

**Comment by pliablepixels** [comment]
Thank you very much! using masonry.js works like a charm! Not quite sure why this is the case but as long as it works :-)
