### ISSUE TITLE
Masonry v4 broke the reload method

### ISSUE THREAD

**Issue by sitecarp** [desandro/masonry#807]
This feature of the previous version of Masonry worked fine. When the height of a "brick" was altered, I just reloaded masonry to shuffle the bricks according to their new heights. With version 4.0.0, the reload method doesn't work. They do update when the viewpane is resized though.

I updated the code to use the new Masonry attribute names. (reload -> reloadItems, gutterWidth -> gutter)

[See fiddle.](https://jsfiddle.net/16odt3t4/)

**Comment by desandro** [comment]
Thanks for reporting this issue. Let's take a look at the modified demo: https://jsfiddle.net/16odt3t4/1/

1. Added a missing `.masonry` container element, so masonry can be initialized and method can be used on the same element.
2. Removed Masonry v2 options, `animatedOptions`, `isAnimated`
3. After changing an item's size, use [`.masonry()`](http://masonry.desandro.com/methods.html#layout-masonry) instead of `reloadItems`. `reloadItems` is useful if you've changed the DOM.

**Comment by sitecarp** [comment]
Wow, thanks for a crazy-fast response!
Yeah, using .masonry() instead of the the reloadItems worked for me! Problem solved.

I also noticed you changed my "gutter" back to "gutterWidth", but "gutter" is working and should be used with v4.0.0, right?

**Comment by desandro** [comment]
Sorry about that. Meant to link to https://jsfiddle.net/16odt3t4/2/ Comment updated.

**Comment by sitecarp** [comment]
Gotcha. No problem!

Did you add some kind of elastic bounce-back to v4? Now on screen resize once the "bricks" reach their location they jump around before settling into place. The only change I made was upgrading from v2 to v4.
[Original here.](http://salisburyonline.sitecarpenter.com/?page=account_create)
[v4.0.0 here.](http://salisburyonline.sitecarpenter.com/account_create.php)

**Comment by desandro** [comment]
Looks the the bounce is happening because of  `transition: all` on `.cms-narrow.border`. All properties are going to be transitioned, so when Masonry changes position, using top/left/and transform, it slides into those changes when they should be done immediately. I'd recommend setting `transition-property` to only the properties you'd like to transition, box-shadow, etc.

**Comment by sitecarp** [comment]
Yep, that was it. Not sure why it didn't effect things with the previous version of masonry.

Well, David, I'm impressed. You created a fantastic feature for free and have gone beyond any level of support that should be expected, especially when it turned out to be my own fault! Thank you so much!

**Comment by desandro** [comment]
:blush:
