### ISSUE TITLE
Masonry with Read More.js

### ISSUE THREAD

**Issue by poojan23** [desandro/masonry#815]
Hi,

I am using masonry v4 for my e commerce website. People will post reviews on the item(s) they like and will be displayed in their profile page. As the reviews will be bigger, I will like to have a particular height set to the <p> tag with a Read More button.

I am using [Jed Foster](http://jedfoster.com/Readmore.js/) plugin called ReadMore.js.

I am calling Masonry.js with imageLoader and recalling the plugin in Read more's beforeToggle & afterToggle. This do work but the height just changes after readmore.js finishes it's slideToggle animation rather than getting animated along. Please help us.

Here is the following [CodePen](http://codepen.io/anon/pen/NxExWy)

Click on read more link to understand our problem better.

Thank you,

**Comment by desandro** [comment]
> This do work but the height just changes after readmore.js finishes it's slideToggle animation rather than getting animated along.

This is the best solution with Masonry and your implementation. In order for Masonry layout to work, it needs the size of item to be set. That's why the animation has to finish.

If you can set the size of the item without the animation, you can animate layout and item at the same time. See [animating item size](http://masonry.desandro.com/extras.html#animating-item-size)
