### ISSUE TITLE
Incorrect vertical spacing (possible font issue?)

### ISSUE THREAD

**Issue by robme** [desandro/masonry#855]
**Test case:** http://codepen.io/robme/pen/EKJmxK

I am having a problem whereby the vertical spacing is sometimes wrong (too large). It happens intermittently when the page is loaded without refreshing, or when it is refreshed. Sometimes it works and sometimes it doesn't.

Here is what it looks like most of the time: http://i.imgur.com/C34gCz5.png
And here is what it looks like when it works: http://i.imgur.com/qIH5Hhi.png

It might be a problem with imagesLoaded. Triggering a masonry('layout') from the console fixes it.

I think the problem is caused by myfonts.com, since it works fine if I remove that code. Any advice on what I can do?

**Comment by desandro** [comment]
Thank you for reporting this issue. Yes, I concur that the problem is with web fonts loading. Unfortunately, the MyFonts service does not have a JavaScript API to listen for font loading, nor does it work with the [Typekit webfontloader](https://github.com/typekit/webfontloader). So we don't have a good solution here. You could try triggering `.masonry()` in a `setTimeout`, but there's no guarantee that this will be at the right time. See demo http://codepen.io/desandro/pen/977322ccc81e6e06b28b0303021751d5/

``` js
  // trigger layout again after 2 second
  setTimeout( function() {
    $masonry.masonry();
  }, 2000 );
```

**Comment by robme** [comment]
Thanks. I will investigate whether we can use another font service. Otherwise setTimeout() might be the only way.

**Comment by TimFletcher** [comment]
Indeed, I had this and was able to resolve it using a zero duration timeout:

```javascript
  setTimeout(function(){
    $masonry.masonry();
  }, 0);
```

**Comment by themesociety** [comment]
Sorry to bring this up again but i had this issue for a long time and what worked very good for me is to layout masonry once all assets are loaded (window load). I thought its a lot saver then the timeout function.

```
jQuery(window).load(function () {
    // layout masonry instance again.
});
```

**Comment by desandro** [comment]
[window.load is a last resort](http://metafizzy.co/blog/window-load-last-resort/)
