### ISSUE TITLE
Masonry layout is creating a unecessary space.

### ISSUE THREAD

**Issue by egucciar** [desandro/masonry#874]
**Test case:** http://codepen.io/anon/pen/jAwRqp

I am really stumped here. Since this is a layout question , you will need to look at my codepen example.

basically, if you see on the second row, there is a giant space between the two blocks. Why? Why doesn't it line up?

Also, fiddle with the width of the third grid-item. Ideally, i want it to be 50% and all my divs will fit together in the space, packed tightly. The reason I have the custom width on it is that 40% is the max width before it moves it to the next row. WHY? It needs to be on the same row. 50% + 50% = 100% so there is room. Why do you think its broken?

**Comment by desandro** [comment]
> if you see on the second row, there is a giant space between the two blocks. Why? Why doesn't it line up?

The space is there because the columnWidth is 20%, but the first item is 50%. a 50% item is rounded up to 60%. So there's 10% extra space.

But if you change `.grid-sizer { width: 10%; }` that will allow 50% item to be measured at 50%. See demo http://codepen.io/desandro/pen/f6815a1b177338f71f6ab9d7722552e7/

**Comment by egucciar** [comment]
thanks so much for responding so quickly! I now understand :)
