### ISSUE TITLE
Images getting out of order which creates blank spaces

### ISSUE THREAD

**Issue by Ankusia** [desandro/masonry#897]
Hello!

After added all the new images to the gallery, everything was displaying perfectly in firefox however in chrome, some blank spaces were appearing and the images were out of order.

I decided to update the versions of masonrygallery and imagesLoaded to the newest ones however after the update now both in Firefox and Chrome the images that should be filling all the space correctly get out of order which creates the blank spaces.

I would be very grateful if you could give me any clues on what could be the cause of this issue and how it can be fixed.

Thanks in advance.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by azasisgod** [comment]
I have had similar issues, and I fixed it by the following code (see bold);

  Masonry.prototype._getItemLayoutPosition = function( item ) {
    item.getSize();
    // how many columns does this brick span
    var remainder = item.size.outerWidth % this.columnWidth;
    var mathMethod = remainder && remainder < 1 ? 'round' : 'ceil';
    // round if off by 1 pixel, otherwise use ceil
    var colSpan = Math[ mathMethod ]( item.size.outerWidth / this.columnWidth );
    colSpan = Math.min( colSpan, this.cols );

    var colGroup = this._getColGroup( colSpan );
    // get the minimum Y value from the columns
    var minimumY = Math.min.apply( Math, colGroup );
    var shortColIndex = colGroup.indexOf( minimumY );
    **this.columnWidth = parseInt(this.columnWidth);**
    // position the brick
    var position = {
      x: this.columnWidth * shortColIndex,
      y: minimumY
    };

    // apply setHeight to necessary columns
    var setHeight = minimumY + item.size.outerHeight;
    **setHeight = parseInt(setHeight);**
    var setSpan = this.cols + 1 - colGroup.length;
    for ( var i = 0; i < setSpan; i++ ) {
      this.colYs[ shortColIndex + i ] = setHeight;
    }
    
    return position;
  };

It seems the problem was with the rounding of pixels of X and Y . 
For example, if there are 4 columns and grid-item width is set to 20% (where the script will convert that to number, depending on the parent's div width, mine ended up as 189.150)
it positions as follow
1) left: 189; (original 189.150)
2) left: 378; (original 189.300)
3) left: 567; (original 189.450)
4) left: 757; (instead of 756) (original 189.600) so it added a pixel

By rounding the 189.150 to 189 always, it fixed the problem.

Same can happen with height. 

Hope it helped.
