### ISSUE TITLE
First load, good, when returning to page, layout broken.

### ISSUE THREAD

**Issue by baidoct** [desandro/masonry#913]
Hi. 

This is really a weird bug which I'm trying to fix since hours and can't find a solution to it. It only happens on Internet Explorer and Edge. 

On the first page load, the layout looks good, as it needs to be. Once you go to a different page, and afterwords you decide to return to the home where the Masonry is, the layout is broken, overlapped. 

The configuration for the plugin is standard. I have also tried with imagesLoaded plugin, but the same problem. 

Here's a live demo: http://adventskalender.mainpost.de/

and here's a video demonstration directly on IE11: https://www.dropbox.com/s/l8eiwchb5yoiygg/bug_explained.mov?dl=0

Any help would be greatly appreciated

**Comment by desandro** [comment]
Sorry, but I will not be able to provide support for this issue. My recommendation is to create  a **reduced test case** to identify where the issue is occuring? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
