### ISSUE TITLE
Issue with webpack

### ISSUE THREAD

**Issue by z1haze** [desandro/masonry#936]
I am pulling in masonry-layout with npm, and then compiling down with webpack. I am using es5 require('masonry-layout') and the bundle file is created successfully without errors, but when trying to initialize masonry I am getting `$(...).masonry is not a function` I have done some research and it seems a lot of people have trouble using this with webpack but I wasnt able to find a solution that would work for me. Can you please help with this?

**Comment by z1haze** [comment]
I got it working with jquery-bridget but can you please at least explain what that is needed? No other jquery plugin has to be loaded this way, its kind of a pain.

**Comment by desandro** [comment]
That's cause Masonry is not a jQuery plugin. It's a JavaScript library that can be used as a jQuery plugin. The jQ plugin functionality is optional, so it's not part of the dependency tree (nor is jQuery). That's why you have to add it separately. jQuery Bridget is mentioned in the [docs for Masonry & Webpack](http://masonry.desandro.com/extras.html#webpack)
