### ISSUE TITLE
Adding new elements fast with shadowDom result in a somewhat broken animation

### ISSUE THREAD

**Issue by daKmoR** [desandro/masonry#988]
I did create a webcomponent with shadow Root for an even easier usage of this awesome piece of code.
and it really works pretty nice :)

You can see it her: https://www.webcomponents.org/element/daKmoR/grain-masonry
before I had sort of my own add animation but now I would like to use the one provided by masonry.
And I somewhat found this strange "bug".

If you go to the 
**Test case:** https://codepen.io/anon/pen/oeaMjx

and click like 2-3 times really fast on the "prepend new items" button there will be some items that from now on misbehave (e.g. a strange post finished animation animation :p) [if you click wait, click wait it works just fine... it's just when you add elements too fast... and yeah this only happen if used inside a custom element - I testet like a lot...)

the code is really the same except that masonry gets created in the custom element and that there is a shadowRoot (but all animated elements are in light dom)

So I'm a little lost here - maybe you got an idea what it could be - I'm great full for any small tip :) 

PS: why does this even matter? because if you create a lot of elements via an external api (e.g. just add divs) and observe the light dom (via webcomponents api) it's like clicking really fast for all those new elements...

**Comment by desandro** [comment]
Thanks for reporting this issue. I have no idea where the issue is. Your example code is identical to the Preprended example code. From what I can tell, there may be an issue with `transitionend` event triggering on items. When you click the button twice, it's happening during a transition. One hack would be to remove transitions with `transitionDuration: 0`. Otherwise, I'm not sure if there's a solid solution here. This may be a webcomponent bug.
