### ISSUE TITLE
Images stacking

### ISSUE THREAD

**Issue by bigthinkery** [desandro/masonry#992]
HI,

I was having an issue with the images flying around but now they are stacking while loading. Not sure how to fix this. Is there any way someone can help? Here is the url:

http://bt-staging.com/work

Thanks

Lisa

**Comment by bigthinkery** [comment]
Anyone have any idea why this is happening? Is there a preloader? I thought I was loading this. Thank you.

**Comment by desandro** [comment]
Everything is working as intended. Here's your code:

``` js
// external js: masonry.pkgd.js, imagesloaded.pkgd.js

// init Masonry
var $grid = $('.grid').masonry({
  itemSelector: '.grid-item',
  percentPosition: true,
  columnWidth: '.grid-sizer'
});
// layout Isotope after all images loaded
$grid.imagesLoaded( function() {
  $grid.masonry();
});
```

This works by first initializing Masonry, then triggering layout again after images have been loaded. Masonry requires images to be loaded in order to correctly position them. 

Otherwise, if you would rather show the images after everything is loaded and ready to go, you can do so with CSS. See demo https://codepen.io/desandro/pen/85aa7f503fa599734b1ecf1f2c76e262/

``` css
.grid {
  background: #DDD;
  transition: opacity 0.4s;
}

.grid.is-invisible {
  opacity: 0;
}
```

``` js
// init Masonry after all images have loaded
var $grid = $('.grid').imagesLoaded( function() {
  $grid.removeClass('is-invisible');
  $grid.masonry({
    itemSelector: '.grid-item',
    percentPosition: true,
    columnWidth: '.grid-sizer'
  }); 
});
```

**Comment by bigthinkery** [comment]
Thank you this fixed my issue!
