### ISSUE TITLE
Set gutter or columnWidth with function

### ISSUE THREAD

**Issue by amerllica** [desandro/masonry#994]
Hi @desandro ,
I wanted to use `function` instead of `number` or `selector` in `gutter` option, but I saw your codes. you didn't use `function` for gutter, in line `1582` for `proto._getMeasurement` function I added a new `else if`.

Actually `else if` added in line `1594`.

my code is :

    else if( typeof option == "function") {
        option = option();
    }

these codes cause to developers could use `function` in `gutter` option.

If you like make me contributor and I fix all options that can use `function`.

**Comment by desandro** [comment]
Hello! Thank you for this suggestion. Masonry v2 actually supported setting `columnWidth` or `gutter` as a function. But I found that using [element sizing](https://masonry.desandro.com/options.html#element-sizing) was more effective as it could be directly set with CSS, rather than having to go through JS.

Thank you for your enthusiasm, but I'll have to pass on this contribution. But please do keep involved in open source 🌈🐻
